
output: Circle.o Ellipse.o Figure.o Rectangle.o MainProgram.o
	g++ -o main Circle.o Ellipse.o Figure.o Rectangle.o MainProgram.o

Circle.o: Circle.cpp Circle.h
	g++ -c Circle.cpp

Ellipse.o: Ellipse.cpp Ellipse.h
	g++ -c Ellipse.cpp

Figure.o: Figure.cpp Figure.h
	g++ -c Figure.cpp 

Rectangle.o: Rectangle.cpp Rectangle.h
	g++ -c Rectangle.cpp

